CREATE DATABASE exam_sys;
/** 管理员表 */
DROP TABLE admin;
CREATE TABLE admin(
	id INT AUTO_INCREMENT COMMENT '管理员ID',
	NAME VARCHAR(30) NOT NULL COMMENT '管理员账号',
	PASSWORD VARCHAR(30) COMMENT '管理员密码',
	CONSTRAINT et_admin_id_pk PRIMARY KEY(id),
	CONSTRAINT et_admin_name_uk UNIQUE(NAME)
);
INSERT INTO admin (NAME, PASSWORD) VALUES('admin', '123456');
SELECT * FROM admin;
COMMIT;